import { ArrowLeft,CheckCircle2,Clock3,ListChecks,WalletCards,Flag,Activity } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { deriveRoadmapMetrics } from '@/features/roadmap/roadmap.metrics'
import { KpiCard } from '@/components/dashboard/KpiCard'
import { OverallProgressCard } from '@/components/dashboard/OverallProgressCard'
import { PaymentCard } from '@/components/payments/PaymentCard'
import { GlossaryText } from '@/components/glossary/GlossaryText'
import { formatSar,pct } from '@/lib/format'

export default function DashboardPage(){const {data,isLoading,error}=useRoadmap(); if(isLoading)return <Loading/>; if(error||!data)return <ErrorState/>; const metrics=deriveRoadmapMetrics(data); const weekLabel=metrics.currentWeek?`الأسبوع الحالي: ${metrics.currentWeek}`:'لم يبدأ بعد'; return <div className="page-shell py-7 sm:py-10">
<section className="mb-7 grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><div className="rounded-3xl bg-primary px-6 py-7 text-primary-foreground sm:px-8 sm:py-9"><span className="text-sm opacity-70">خارطة التنفيذ المباشرة</span><h1 className="mt-3 max-w-3xl text-4xl font-black leading-[1.25] sm:text-5xl">مشروع عقاراتي<br/><span className="font-light opacity-80">من الخطة إلى الإطلاق.</span></h1><p className="mt-5 max-w-2xl text-sm leading-8 opacity-80 sm:text-base"><GlossaryText text={data.project.description}/></p><div className="mt-7 flex flex-wrap gap-2"><Link to="/timeline" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary-foreground px-4 font-bold text-primary"><Activity className="h-4 w-4"/>عرض الخطة الزمنية</Link><span className="inline-flex min-h-11 items-center rounded-xl border border-white/20 px-4 text-sm">{weekLabel}</span></div></div><div className="surface rounded-3xl p-6"><span className="eyebrow">مدة التنفيذ</span><div className="mt-5 flex items-end gap-3"><b className="metric-number text-6xl font-black">10</b><span className="mb-1 text-muted-foreground">أسابيع مستهدفة</span></div><div className="mt-7 rounded-2xl bg-warning/10 p-4"><b className="block text-warning">+ أسبوعان للقبول النهائي</b><span className="mt-2 block text-sm leading-7 text-muted-foreground">الأسبوعان 11–12 مخصصان للاختبارات النهائية ومعالجة ملاحظات القبول عند الحاجة.</span></div></div></section>
<div className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="التقدم العام" value={pct(metrics.overallProgress)} detail={metrics.currentWeek?`الأسبوع ${metrics.currentWeek} من ${data.project.target_weeks}`:'المشروع لم يبدأ بعد'} icon={Activity}/><KpiCard label="المهام المكتملة" value={`${metrics.doneTasks}`} detail={`من أصل ${metrics.totalTasks} مهمة`} icon={CheckCircle2}/><KpiCard label="قيد التنفيذ" value={`${metrics.activeTasks}`} detail="تنفيذ أو مراجعة" icon={ListChecks}/><KpiCard label="المدفوع" value={formatSar(metrics.paidAmount)} detail={`من ${formatSar(data.project.total_amount)}`} icon={WalletCards}/><KpiCard label="المحطة القادمة" value={metrics.nextMilestone?`أسبوع ${metrics.nextMilestone.week}`:'—'} detail={metrics.nextMilestone?.title??'لا توجد'} icon={Flag}/></div>
<div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><OverallProgressCard value={metrics.overallProgress} currentWeek={metrics.currentWeek}/><section className="surface rounded-3xl p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><span className="eyebrow">المسارات</span><h2 className="mt-1 text-2xl font-black">تقدم المراحل</h2></div><Link to="/timeline" className="inline-flex min-h-11 items-center gap-1 rounded-xl px-3 text-sm font-bold hover:bg-secondary">التفاصيل<ArrowLeft className="h-4 w-4"/></Link></div><div className="mt-6 space-y-5">{data.phases.slice(0,8).map(p=><div key={p.id}><div className="mb-2 flex justify-between gap-3 text-sm"><span className="min-w-0 font-bold"><GlossaryText text={p.name}/></span><span className="text-muted-foreground">{pct(p.progress)}</span></div><div className="h-2 rounded-full bg-secondary"><div className="h-2 rounded-full bg-primary" style={{width:`${p.progress}%`}}/></div></div>)}</div></section></div>
<section className="mt-5 grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><div className="surface rounded-3xl p-6"><span className="eyebrow">القيمة التعاقدية</span><div className="mt-3 text-4xl font-black">{formatSar(data.project.total_amount)}</div><p className="mt-3 text-sm leading-7 text-muted-foreground">ثلاث دفعات مرتبطة ببوابات إنجاز وقبول واضحة.</p><Link to="/payments" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground">تفاصيل الدفعات<ArrowLeft className="h-4 w-4"/></Link></div><div className="grid gap-4 md:grid-cols-3">{data.payments.map(p=><PaymentCard key={p.id} payment={p}/>)}</div></section>
<section className="mt-5 surface rounded-3xl p-6"><div className="flex items-center justify-between gap-4"><div><span className="eyebrow">آخر المستجدات</span><h2 className="mt-1 text-2xl font-black">سجل التقدم</h2></div><Clock3 className="h-5 w-5 text-muted-foreground"/></div>{data.updates.length?<div className="mt-6 grid gap-4 md:grid-cols-2">{data.updates.slice(0,4).map(u=><article key={u.id} className="rounded-2xl bg-secondary/40 p-4"><span className="text-xs text-muted-foreground">{new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(u.created_at))}</span><h3 className="mt-2 font-black"><GlossaryText text={u.title}/></h3><p className="mt-3 text-sm leading-7 text-muted-foreground"><GlossaryText text={u.body}/></p></article>)}</div>:<div className="mt-6 rounded-2xl border border-dashed p-6 text-sm leading-7 text-muted-foreground">لا توجد تحديثات منشورة بعد. ستظهر هنا التحديثات التي تضيفها من لوحة الإدارة.</div>}</section>
</div>}
function Loading(){return <div className="page-shell py-20"><div className="h-56 animate-pulse rounded-3xl bg-secondary"/></div>}
function ErrorState(){return <div className="page-shell py-20"><div className="surface rounded-3xl p-8"><h1 className="text-2xl font-black">تعذر تحميل بيانات الخطة</h1><p className="mt-3 leading-7 text-muted-foreground">أعد المحاولة بعد قليل.</p></div></div>}
