import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createClient, type Session } from '@supabase/supabase-js'
import { Activity, BarChart3, CalendarRange, CheckCircle2, Circle, Clock3, CreditCard, FileCheck2, History, LayoutDashboard, ListChecks, LockKeyhole, LogOut, Menu, Moon, Settings, ShieldCheck, Sun, WalletCards, X } from 'lucide-react'
import './styles/globals.css'

type Status='planned'|'active'|'review'|'done'|'blocked'
type PhaseStatus='planned'|'active'|'done'|'blocked'
type PayStatus='pending'|'due'|'paid'
type Project={id:string;slug:string;name:string;description:string;target_weeks:number;max_weeks:number;total_amount:number;currency:string;overall_progress:number;current_week:number}
type Phase={id:string;project_id:string;name:string;description:string;start_week:number;end_week:number;progress:number;status:PhaseStatus;sort_order:number;is_public:boolean}
type Task={id:string;project_id:string;phase_id:string;title:string;description:string;week:number;progress:number;status:Status;priority:'low'|'medium'|'high'|'critical';owner_label:string;notes:string;is_public:boolean}
type Payment={id:string;project_id:string;sequence:number;percentage:number;amount:number;trigger_title:string;trigger_week:number|null;status:PayStatus;notes:string;paid_at:string|null}
type Milestone={id:string;project_id:string;title:string;week:number;status:'upcoming'|'ready'|'approved'|'delayed';acceptance_summary:string;sort_order:number}
type Deliverable={id:string;project_id:string;group_key:'scope'|'alpha'|'rc'|'final';title:string;is_complete:boolean;sort_order:number}
type Update={id:string;project_id:string;title:string;body:string;published:boolean;created_at:string;related_phase_id:string|null}
type Data={project:Project;phases:Phase[];tasks:Task[];payments:Payment[];milestones:Milestone[];deliverables:Deliverable[];updates:Update[]}

const PROJECT='11111111-1111-4111-8111-111111111111'
const phaseRows:[string,string,string,number,number,number,PhaseStatus][]=[
['p1','التحليل وتثبيت النطاق','تحويل المتطلبات إلى نطاق نهائي ومعايير قبول.',1,2,100,'done'],['p2','UX/UI + SaaS/PWA','نظام تصميم RTL وتجربة المنصة على جميع الشاشات.',1,4,82,'active'],['p3','البنية التقنية والأمان','Supabase والمصادقة والصلاحيات والنشر.',1,3,78,'active'],['p4','دفتر العقارات والملاك','العقارات والصور والبحث وبيانات الملاك.',2,5,56,'active'],['p5','الباحثون والعملاء','ملفات الباحثين والاحتياجات والميزانية.',3,5,38,'active'],['p6','القروبات والدعوات','قروبات 1–10 أعضاء والدعوات والأدوار.',4,7,18,'active'],['p7','الاشتراكات والدفع','Free / Pro / Group والحدود والإضافات.',5,7,0,'planned'],['p8','المشاركة والخصوصية','مشاركة آمنة وإخفاء بيانات المالك.',4,7,16,'active'],['p9','التنبيهات والبحث المحفوظ','Saved Search وتنبيهات فرص الباحثين.',6,8,0,'planned'],['p10','AI Matching','مطابقة الباحث بالعقار مع تفسير التوافق.',7,9,0,'planned'],['p11','التكامل والاختبار والإطلاق','اختبارات شاملة وRelease Candidate.',8,10,0,'planned']]
const phases:Phase[]=phaseRows.map((x,i)=>({id:x[0],project_id:PROJECT,name:x[1],description:x[2],start_week:x[3],end_week:x[4],progress:x[5],status:x[6],sort_order:i+1,is_public:true}))
const taskRows:[string,string,string,number,number,Status,Task['priority'],string][]=[
['t1','p1','اعتماد نطاق الإصدار وخطة القبول',1,100,'done','critical','Product'],['t2','p2','Design System عربي RTL والوضع الليلي',2,90,'review','high','Frontend'],['t3','p3','تهيئة Supabase وRLS وRealtime',2,70,'active','critical','Backend'],['t4','p4','CRUD العقارات والصور والحالات',3,55,'active','critical','Backend'],['t5','p5','ملف الباحث واحتياجاته وميزانيته',4,35,'active','high','Product / QA'],['t6','p8','إخفاء المالك من العرض العام',4,30,'active','critical','Backend'],['t7','p6','إنشاء القروب والدعوات والأدوار',5,20,'active','high','Frontend'],['t8','p7','الباقات والحدود وUpgrade Nudge',6,0,'planned','high','Backend'],['t9','p8','رابط مشاركة عام Show / Hide',7,0,'planned','high','Frontend'],['t10','p9','التنبيهات والبحث المحفوظ Pro',8,0,'planned','high','Backend'],['t11','p10','محرك المطابقة والقواعد وAI Rerank',9,0,'planned','critical','Backend'],['t12','p11','Release Candidate والتسليم',10,0,'planned','critical','Product / QA']]
const tasks:Task[]=taskRows.map(x=>({id:x[0],project_id:PROJECT,phase_id:x[1],title:x[2],description:'مهمة تنفيذية ضمن الخطة الزمنية المعتمدة.',week:x[3],progress:x[4],status:x[5],priority:x[6],owner_label:x[7],notes:'',is_public:true}))
const seed:Data={
 project:{id:PROJECT,slug:'aqarati-roadmap',name:'عقاراتي',description:'خارطة تنفيذ تفاعلية لمشروع عقاراتي — عرض مباشر للعميل وإدارة تقدم خاصة بصاحب المشروع.',target_weeks:10,max_weeks:12,total_amount:7800,currency:'SAR',overall_progress:34,current_week:2},
 phases,tasks,
 payments:[{id:'pay1',project_id:PROJECT,sequence:1,percentage:40,amount:3120,trigger_title:'مقدم عند بدء المشروع',trigger_week:1,status:'paid',notes:'تُستحق عند اعتماد بدء المشروع وتثبيت النطاق.',paid_at:null},{id:'pay2',project_id:PROJECT,sequence:2,percentage:30,amount:2340,trigger_title:'بعد اعتماد نسخة Alpha',trigger_week:5,status:'pending',notes:'بعد قبول مخرجات Alpha بنهاية الأسبوع الخامس.',paid_at:null},{id:'pay3',project_id:PROJECT,sequence:3,percentage:30,amount:2340,trigger_title:'بعد Release Candidate والتسليم النهائي',trigger_week:10,status:'pending',notes:'بنهاية الأسبوع 10، أو خلال هامش الأسبوعين 11–12 عند استخدامه للاختبارات والقبول.',paid_at:null}],
 milestones:[{id:'m1',project_id:PROJECT,title:'اعتماد النطاق',week:1,status:'approved',acceptance_summary:'Scope / Backlog ونموذج البيانات معتمد.',sort_order:1},{id:'m2',project_id:PROJECT,title:'Alpha Core',week:5,status:'upcoming',acceptance_summary:'دفتر العقارات + الباحثون + القروب الأساسي قابل للاستعراض.',sort_order:2},{id:'m3',project_id:PROJECT,title:'Billing Beta',week:7,status:'upcoming',acceptance_summary:'الباقات والحدود والإضافات والمشاركة الآمنة جاهزة.',sort_order:3},{id:'m4',project_id:PROJECT,title:'AI Pro Beta',week:9,status:'upcoming',acceptance_summary:'محرك المطابقة يعمل بحصص وسبب توافق واضح.',sort_order:4},{id:'m5',project_id:PROJECT,title:'Release Candidate',week:10,status:'upcoming',acceptance_summary:'النسخة المرشحة للإطلاق تحقق معايير القبول.',sort_order:5}],
 deliverables:[['d1','scope','النطاق النهائي وBacklog ونماذج البيانات',true],['d2','scope','نظام التصميم وتجربة RTL الأساسية',true],['d3','alpha','إضافة وتعديل وبحث العقارات',false],['d4','alpha','ملفات الباحثين وبيانات الملاك والخصوصية',false],['d5','alpha','القروب والدعوات والأدوار الأساسية',false],['d6','rc','الباقات والحدود والإضافات',false],['d7','rc','التنبيهات والبحث المحفوظ',false],['d8','rc','AI Matching وتفسير درجة التوافق',false],['d9','rc','اختبارات E2E والأمان والاستجابة',false],['d10','final','تسليم الكود والمستودع وبيئة الإنتاج',false],['d11','final','توثيق الإدارة والتشغيل ومعايير القبول',false]].map((x,i)=>({id:String(x[0]),project_id:PROJECT,group_key:x[1] as Deliverable['group_key'],title:String(x[2]),is_complete:Boolean(x[3]),sort_order:i+1})),
 updates:[{id:'u1',project_id:PROJECT,title:'اعتماد الخطة الزمنية والدفعات',body:'تم اعتماد خطة تنفيذ مكثفة من 10 أسابيع مع هامش قبول حتى 12 أسبوعًا، وربط الدفعات ببوابات إنجاز واضحة.',published:true,related_phase_id:'p1',created_at:'2026-08-30T18:00:00Z'},{id:'u2',project_id:PROJECT,title:'بدء تصميم منصة المتابعة',body:'تم تثبيت الهوية البصرية، العربية RTL، الوضعين الليلي والنهاري، ونموذج العرض العام للعميل.',published:true,related_phase_id:'p2',created_at:'2026-08-30T20:00:00Z'}]
}

const sbUrl=import.meta.env.VITE_SUPABASE_URL as string|undefined
const sbKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string|undefined
const supabase=sbUrl&&sbKey?createClient(sbUrl,sbKey):null
const qkey=['roadmap','aqarati-roadmap'] as const
const money=(n:number)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n)
const pct=(n:number)=>`${Math.round(n)}٪`
const statusLabel:Record<string,string>={planned:'مخططة',active:'قيد التنفيذ',review:'مراجعة',done:'مكتملة',blocked:'متوقفة',pending:'قادمة',due:'مستحقة',paid:'مدفوعة'}

async function loadData():Promise<Data>{
 if(!supabase)return structuredClone(seed)
 const [{data:project,error:e0},{data:phases,error:e1},{data:tasks,error:e2},{data:payments,error:e3},{data:milestones,error:e4},{data:deliverables,error:e5},{data:updates,error:e6}]=await Promise.all([
  supabase.from('projects').select('*').eq('slug','aqarati-roadmap').single(),supabase.from('phases').select('*').order('sort_order'),supabase.from('tasks').select('*').order('week'),supabase.from('payments').select('*').order('sequence'),supabase.from('milestones').select('*').order('sort_order'),supabase.from('deliverables').select('*').order('sort_order'),supabase.from('updates').select('*').eq('published',true).order('created_at',{ascending:false})])
 const err=e0||e1||e2||e3||e4||e5||e6;if(err)throw err
 return {project,phases:phases??[],tasks:tasks??[],payments:payments??[],milestones:milestones??[],deliverables:deliverables??[],updates:updates??[]}
}
function useRoadmap(){return useQuery({queryKey:qkey,queryFn:loadData,staleTime:20000,refetchInterval:60000})}
function useRealtime(){const qc=useQueryClient();useEffect(()=>{if(!supabase)return;const ch=supabase.channel('roadmap-live').on('postgres_changes',{event:'*',schema:'public'},()=>void qc.invalidateQueries({queryKey:qkey})).subscribe();return()=>{void supabase.removeChannel(ch)}},[qc])}

function ThemeToggle(){const [dark,setDark]=useState(()=>localStorage.getItem('aqarati-theme')==='dark'||(!localStorage.getItem('aqarati-theme')&&matchMedia('(prefers-color-scheme: dark)').matches));useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('aqarati-theme',dark?'dark':'light')},[dark]);return <button className="icon-btn" aria-label="تبديل الوضع" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>}
const nav=[['/','الملخص',BarChart3],['/timeline','الخطة الزمنية',CalendarRange],['/tasks','المهام',ListChecks],['/payments','الدفعات',CreditCard],['/deliverables','التسليمات',FileCheck2],['/updates','التحديثات',History]] as const
function Shell({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);return <div className="app"><header className="topbar"><div className="shell bar"><Link to="/" className="brand"><span className="brand-icon"><ShieldCheck size={20}/></span><span><b>عقاراتي</b><small>خارطة التنفيذ المباشرة</small></span></Link><nav className="desktop-nav">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>isActive?'nav-item active':'nav-item'}><Icon size={16}/>{label}</NavLink>)}</nav><div className="bar-actions"><ThemeToggle/><Link to="/login" className="outline-btn">دخول الإدارة</Link><button className="icon-btn mobile-only" onClick={()=>setOpen(v=>!v)}>{open?<X size={19}/>:<Menu size={19}/>}</button></div></div>{open&&<nav className="mobile-menu shell">{nav.map(([to,label,Icon])=><NavLink onClick={()=>setOpen(false)} key={to} to={to} className="mobile-link"><Icon size={17}/>{label}</NavLink>)}</nav>}</header><main>{children}</main><footer><div className="shell footer-row"><span>عقاراتي — متابعة تنفيذ المشروع</span><span>عرض مباشر للعميل • قراءة فقط</span></div></footer></div>}
function PageHead({icon:Icon,kicker,title,text}:{icon:any;kicker:string;title:string;text:string}){return <header className="page-head"><div className="kicker"><Icon size={19}/>{kicker}</div><h1>{title}</h1><p>{text}</p></header>}
function Kpi({label,value,detail,icon:Icon}:{label:string;value:string;detail:string;icon:any}){return <article className="card kpi"><div className="kpi-top"><span>{label}</span><i><Icon size={19}/></i></div><strong>{value}</strong><small>{detail}</small></article>}
function ProgressBar({value}:{value:number}){return <div className="progress"><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function Loading(){return <div className="shell page"><div className="skeleton"/></div>}

function Dashboard(){const {data,isLoading}=useRoadmap();if(isLoading||!data)return <Loading/>;const done=data.tasks.filter(t=>t.status==='done').length,active=data.tasks.filter(t=>['active','review'].includes(t.status)).length,paid=data.payments.filter(p=>p.status==='paid').reduce((s,p)=>s+p.amount,0),next=data.milestones.find(m=>m.status!=='approved');return <Shell><div className="shell page"><section className="hero-grid"><div className="hero"><span>خارطة التنفيذ المباشرة</span><h1>مشروع عقاراتي<br/><em>من الخطة إلى الإطلاق.</em></h1><p>{data.project.description}</p><div className="hero-actions"><Link className="light-btn" to="/timeline"><Activity size={17}/>عرض الخطة الزمنية</Link><span>الأسبوع الحالي: {data.project.current_week}</span></div></div><aside className="card duration"><span>مدة التنفيذ</span><div><b>10</b><small>أسابيع مستهدفة</small></div><p><strong>+ أسبوعان هامش قبول</strong>الأسبوعان 11–12 للاختبارات وUAT والإصلاحات فقط.</p></aside></section><section className="kpi-grid"><Kpi label="التقدم العام" value={pct(data.project.overall_progress)} detail={`الأسبوع ${data.project.current_week} من 10`} icon={Activity}/><Kpi label="المهام المكتملة" value={`${done}`} detail={`من أصل ${data.tasks.length} مهمة`} icon={CheckCircle2}/><Kpi label="قيد التنفيذ" value={`${active}`} detail="تنفيذ أو مراجعة" icon={ListChecks}/><Kpi label="المدفوع" value={money(paid)} detail={`من ${money(data.project.total_amount)}`} icon={WalletCards}/></section><section className="two-col"><article className="card pad"><span className="eyebrow">التقدم العام</span><div className="progress-head"><div><h2>المشروع يتحرك وفق الخطة</h2><p>يتم تحديث الحالة من لوحة الإدارة وتظهر للعميل مباشرة.</p></div><strong>{pct(data.project.overall_progress)}</strong></div><ProgressBar value={data.project.overall_progress}/><div className="week-band"><span style={{gridColumn:'span 10'}}/><i style={{gridColumn:'span 2'}}/></div><div className="week-legend"><span>10 أسابيع تنفيذ</span><span>أسبوعان UAT فقط</span></div></article><article className="card pad"><div className="section-title"><div><span className="eyebrow">المسارات</span><h2>تقدم المراحل</h2></div><Link to="/timeline">التفاصيل</Link></div><div className="phase-list">{data.phases.slice(0,7).map(p=><div key={p.id}><div><b>{p.name}</b><span>{pct(p.progress)}</span></div><ProgressBar value={p.progress}/></div>)}</div></article></section><section className="card pad updates-preview"><div className="section-title"><div><span className="eyebrow">آخر المستجدات</span><h2>سجل التقدم</h2></div>{next&&<span className="pill">المحطة القادمة: {next.title} — أسبوع {next.week}</span>}</div><div className="updates-grid">{data.updates.slice(0,4).map(u=><article key={u.id}><time>{new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(u.created_at))}</time><h3>{u.title}</h3><p>{u.body}</p></article>)}</div></section></div></Shell>}
function Timeline(){const {data}=useRoadmap();if(!data)return <Loading/>;return <Shell><div className="shell page"><PageHead icon={CalendarRange} kicker="10 + 2 أسابيع" title="الخطة الزمنية" text="المسارات تعمل بالتوازي للوصول إلى Release Candidate في نهاية الأسبوع العاشر، مع أسبوعين إضافيين للقبول والإصلاحات فقط."/><div className="notice"><strong>هامش القبول ليس تمديدًا للنطاق.</strong> لا تضاف ميزات جديدة في الأسبوعين 11–12.</div><div className="gantt-wrap"><div className="gantt"><div className="gantt-head"><b>المسار</b>{Array.from({length:12},(_,i)=><span key={i} className={i>=10?'uat':''}>{i+1}</span>)}</div>{data.phases.map(p=><div className="gantt-row" key={p.id}><div className="g-label"><b>{p.name}</b><span>{pct(p.progress)}</span></div>{Array.from({length:12},(_,i)=>{const w=i+1,a=w>=p.start_week&&w<=p.end_week;return <span key={w} className={`${a?'on':''} ${i>=10?'uat':''}`}/>})}</div>)}</div></div><h2 className="subhead">بوابات الإنجاز</h2><div className="milestone-grid">{data.milestones.map(m=><article className="card pad" key={m.id}><small>الأسبوع {m.week}</small><h3>{m.title}</h3><p>{m.acceptance_summary}</p></article>)}</div></div></Shell>}
function Tasks(){const {data}=useRoadmap();const[q,setQ]=useState('');const[st,setSt]=useState('all');const list=useMemo(()=>data?.tasks.filter(t=>(!q||t.title.includes(q))&&(st==='all'||t.status===st))??[],[data,q,st]);if(!data)return <Loading/>;return <Shell><div className="shell page"><PageHead icon={ListChecks} kicker="متابعة التنفيذ" title="المهام" text="تفصيل العمل المخطط والمنفذ، مع الحالة ونسبة التقدم لكل مهمة."/><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في المهام..."/><select value={st} onChange={e=>setSt(e.target.value)}><option value="all">كل الحالات</option><option value="planned">مخططة</option><option value="active">قيد التنفيذ</option><option value="review">مراجعة</option><option value="done">مكتملة</option><option value="blocked">متوقفة</option></select></div><div className="task-list">{list.map(t=><article className="card task" key={t.id}><div><small>الأسبوع {t.week} · {data.phases.find(p=>p.id===t.phase_id)?.name}</small><h3>{t.title}</h3><span>{t.owner_label}</span></div><div className="task-progress"><b>{pct(t.progress)}</b><ProgressBar value={t.progress}/><small>{statusLabel[t.status]}</small></div></article>)}</div></div></Shell>}
function PaymentCard({p}:{p:Payment}){return <article className="card pay-card"><div><span>الدفعة {p.sequence}</span><b>{p.percentage}٪ — {money(p.amount)}</b></div><i className={`pay ${p.status}`}>{statusLabel[p.status]}</i><hr/><h3>{p.trigger_title}</h3><p>{p.notes}</p>{p.trigger_week&&<small>بوابة الأسبوع {p.trigger_week}</small>}</article>}
function Payments(){const {data}=useRoadmap();if(!data)return <Loading/>;const paid=data.payments.filter(p=>p.status==='paid').reduce((s,p)=>s+p.amount,0);return <Shell><div className="shell page"><PageHead icon={CreditCard} kicker="جدول مالي مرتبط بالإنجاز" title="الدفعات" text={`قيمة المشروع ${money(data.project.total_amount)}، موزعة 40% / 30% / 30%.`}/><div className="money-stats"><Kpi label="القيمة الإجمالية" value={money(data.project.total_amount)} detail="قيمة المشروع" icon={CreditCard}/><Kpi label="تم دفعه" value={money(paid)} detail="حتى الآن" icon={CheckCircle2}/><Kpi label="المتبقي" value={money(data.project.total_amount-paid)} detail="مرتبط ببوابات القبول" icon={Clock3}/></div><div className="payment-grid">{data.payments.map(p=><PaymentCard p={p} key={p.id}/>)}</div></div></Shell>}
function Deliverables(){const {data}=useRoadmap();if(!data)return <Loading/>;const labels={scope:'اعتماد النطاق',alpha:'بوابة Alpha — الأسبوع 5',rc:'Release Candidate — الأسبوع 10',final:'التسليم النهائي'};return <Shell><div className="shell page"><PageHead icon={FileCheck2} kicker="معايير القبول" title="التسليمات" text="ما الذي يجب أن يكون جاهزًا عند كل بوابة قبل اعتبارها مقبولة."/><div className="deliver-grid">{Object.entries(labels).map(([key,label])=><section className="card pad" key={key}><h2>{label}</h2><div className="check-list">{data.deliverables.filter(d=>d.group_key===key).map(d=><div key={d.id}>{d.is_complete?<CheckCircle2 className="done" size={20}/>:<Circle size={20}/>}<span>{d.title}</span></div>)}</div></section>)}</div></div></Shell>}
function Updates(){const {data}=useRoadmap();if(!data)return <Loading/>;return <Shell><div className="shell page"><PageHead icon={History} kicker="سجل شفاف للعميل" title="التحديثات" text="كل تحديث منشور يظهر هنا بترتيب زمني من الأحدث إلى الأقدم."/><div className="timeline-list">{data.updates.map(u=><article className="card pad" key={u.id}><time>{new Intl.DateTimeFormat('ar-SA',{dateStyle:'full'}).format(new Date(u.created_at))}</time><h2>{u.title}</h2><p>{u.body}</p></article>)}</div></div></Shell>}

function useSession(){const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(Boolean(supabase));useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const sub=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)).data.subscription;return()=>sub.unsubscribe()},[]);return{session,loading}}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const navg=useNavigate();const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase){setError('لم يتم ربط Supabase بعد.');return}setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError('تعذر تسجيل الدخول. تحقق من البيانات.');else navg('/admin')};return <div className="login-page"><div className="login-top shell"><Link to="/">العودة للعرض</Link><ThemeToggle/></div><div className="login-grid shell"><aside><ShieldCheck size={38}/><h1>لوحة تحكمك<br/><em>تبقى خاصة بك.</em></h1><p>عدّل التقدم والحالات والدفعات والتحديثات. العميل يرى النتيجة فقط.</p></aside><form className="card login-card" onSubmit={submit}><LockKeyhole size={28}/><h2>دخول الإدارة</h2><p>حساب واحد خاص بصاحب المشروع.</p>{!supabase&&<div className="notice">بيئة Supabase لم تُضبط بعد.</div>}<label>البريد الإلكتروني<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>كلمة المرور<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<span className="error">{error}</span>}<button disabled={busy} className="primary-btn">{busy?'جارٍ الدخول…':'تسجيل الدخول'}</button></form></div></div>}
const adminNav=[['/admin','الملخص',LayoutDashboard],['/admin/tasks','المهام',ListChecks],['/admin/timeline','الخطة',CalendarRange],['/admin/payments','الدفعات',CreditCard],['/admin/updates','التحديثات',History],['/admin/settings','الإعدادات',Settings]] as const
function Protected({children}:{children:React.ReactNode}){const{session,loading}=useSession();if(loading)return <Loading/>;return session?children:<Navigate to="/login" replace/>}
function AdminShell({children}:{children:React.ReactNode}){const navg=useNavigate();const out=async()=>{await supabase?.auth.signOut();navg('/login')};return <div className="admin-layout"><aside className="admin-side"><Link className="admin-brand" to="/admin"><span>ع</span><div><b>إدارة عقاراتي</b><small>لوحة المالك</small></div></Link><nav>{adminNav.map(([to,label,Icon])=><NavLink end={to==='/admin'} key={to} to={to}><Icon size={17}/>{label}</NavLink>)}</nav><div className="admin-bottom"><Link to="/">عرض العميل</Link><button onClick={out}><LogOut size={17}/>تسجيل الخروج</button></div></aside><main className="admin-main"><header><div><b>لوحة إدارة المشروع</b><small>التغييرات تنعكس على عرض العميل</small></div><ThemeToggle/></header><div className="admin-content">{children}</div></main></div>}
function AdminHead({title,text}:{title:string;text:string}){return <div className="admin-head"><span>الإدارة</span><h1>{title}</h1><p>{text}</p></div>}
function useAdminData(){const q=useRoadmap(),qc=useQueryClient();const inv=()=>qc.invalidateQueries({queryKey:qkey});const task=useMutation({mutationFn:async({id,patch}:{id:string;patch:Partial<Task>})=>{if(!supabase)throw new Error('Supabase غير متصل');const{error}=await supabase.from('tasks').update(patch).eq('id',id);if(error)throw error},onSuccess:inv});const phase=useMutation({mutationFn:async({id,patch}:{id:string;patch:Partial<Phase>})=>{if(!supabase)throw new Error('Supabase غير متصل');const{error}=await supabase.from('phases').update(patch).eq('id',id);if(error)throw error},onSuccess:inv});const pay=useMutation({mutationFn:async({id,patch}:{id:string;patch:Partial<Payment>})=>{if(!supabase)throw new Error('Supabase غير متصل');const{error}=await supabase.from('payments').update(patch).eq('id',id);if(error)throw error},onSuccess:inv});return{...q,task,phase,pay,inv}}
function AdminHome(){const{data}=useAdminData();if(!data)return <Loading/>;return <AdminShell><AdminHead title="لوحة الإدارة" text="ملخص سريع لما سيراه العميل وما يحتاج تدخلًا منك."/><div className={`notice ${supabase?'ok':''}`}>{supabase?'Supabase متصل — التعديلات ستظهر للعميل مباشرة.':'Supabase غير متصل بعد.'}</div><div className="kpi-grid"><Kpi label="التقدم" value={pct(data.project.overall_progress)} detail={`الأسبوع ${data.project.current_week}`} icon={Activity}/><Kpi label="المهام" value={`${data.tasks.length}`} detail="مهمة تنفيذية" icon={ListChecks}/><Kpi label="قيمة العقد" value={money(data.project.total_amount)} detail="3 دفعات" icon={CreditCard}/><Kpi label="الوصول العام" value="Read only" detail="لا تعديل للعميل" icon={ShieldCheck}/></div></AdminShell>}
function AdminTasks(){const{data,task}=useAdminData();if(!data)return <Loading/>;return <AdminShell><AdminHead title="إدارة المهام" text="غيّر الحالة ونسبة الإنجاز؛ الحفظ يتم مباشرة."/><div className="admin-list">{data.tasks.map(t=><article className="card admin-row" key={t.id}><div><small>الأسبوع {t.week}</small><h3>{t.title}</h3></div><select value={t.status} onChange={e=>task.mutate({id:t.id,patch:{status:e.target.value as Status}})}>{['planned','active','review','done','blocked'].map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select><label><input type="range" min="0" max="100" step="5" value={t.progress} onChange={e=>task.mutate({id:t.id,patch:{progress:Number(e.target.value)}})}/><b>{pct(t.progress)}</b></label></article>)}</div></AdminShell>}
function AdminTimeline(){const{data,phase}=useAdminData();if(!data)return <Loading/>;return <AdminShell><AdminHead title="إدارة الخطة الزمنية" text="حدّث تقدم كل مسار دون تغيير نطاق الأسابيع المعتمد."/><div className="deliver-grid">{data.phases.map(p=><article className="card pad" key={p.id}><small>الأسبوع {p.start_week}–{p.end_week}</small><h3>{p.name}</h3><p>{p.description}</p><label className="range-row"><input type="range" min="0" max="100" step="5" value={p.progress} onChange={e=>phase.mutate({id:p.id,patch:{progress:Number(e.target.value)}})}/><b>{pct(p.progress)}</b></label></article>)}</div></AdminShell>}
function AdminPayments(){const{data,pay}=useAdminData();if(!data)return <Loading/>;return <AdminShell><AdminHead title="إدارة الدفعات" text="تحديث حالة الدفعة للعرض فقط، دون معالجة مالية."/><div className="payment-grid">{data.payments.map(p=><div key={p.id}><PaymentCard p={p}/><select className="wide-select" value={p.status} onChange={e=>pay.mutate({id:p.id,patch:{status:e.target.value as PayStatus,paid_at:e.target.value==='paid'?new Date().toISOString():null}})}><option value="pending">قادمة</option><option value="due">مستحقة</option><option value="paid">مدفوعة</option></select></div>)}</div></AdminShell>}
function AdminUpdates(){const{data,inv}=useAdminData();const[title,setTitle]=useState(''),[body,setBody]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;const{error}=await supabase.from('updates').insert({project_id:PROJECT,title,body,published:true});if(!error){setTitle('');setBody('');inv()}};return <AdminShell><AdminHead title="التحديثات" text="انشر تحديثًا مختصرًا وشفافًا للعميل."/><form className="card update-form" onSubmit={submit}><label>العنوان<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>التفاصيل<textarea value={body} onChange={e=>setBody(e.target.value)} required/></label><button className="primary-btn">نشر للعميل</button></form><div className="timeline-list">{data?.updates.map(u=><article className="card pad" key={u.id}><h3>{u.title}</h3><p>{u.body}</p></article>)}</div></AdminShell>}
function AdminSettings(){return <AdminShell><AdminHead title="الإعدادات" text="هوية المشروع واتصال البيانات."/><div className="deliver-grid"><article className="card pad"><h3>Supabase</h3><p>{supabase?'متصل عبر متغيرات البيئة.':'غير متصل — أضف VITE_SUPABASE_URL وVITE_SUPABASE_PUBLISHABLE_KEY.'}</p></article><article className="card pad"><h3>الهوية</h3><p>Deep Amethyst #3E1848 + Whisper Lavender #E7E6F5 + خط ثمانية Serif Display.</p></article><article className="card pad"><h3>الأمان</h3><p>العرض العام Read Only؛ الإدارة تعتمد Auth + RLS.</p></article></div></AdminShell>}
function Realtime(){useRealtime();return null}

const qc=new QueryClient({defaultOptions:{queries:{retry:1,refetchOnWindowFocus:true}}})
function App(){return <QueryClientProvider client={qc}><BrowserRouter><Realtime/><Routes><Route path="/" element={<Dashboard/>}/><Route path="/timeline" element={<Timeline/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/payments" element={<Payments/>}/><Route path="/deliverables" element={<Deliverables/>}/><Route path="/updates" element={<Updates/>}/><Route path="/login" element={<Login/>}/><Route path="/admin" element={<Protected><AdminHome/></Protected>}/><Route path="/admin/tasks" element={<Protected><AdminTasks/></Protected>}/><Route path="/admin/timeline" element={<Protected><AdminTimeline/></Protected>}/><Route path="/admin/payments" element={<Protected><AdminPayments/></Protected>}/><Route path="/admin/updates" element={<Protected><AdminUpdates/></Protected>}/><Route path="/admin/settings" element={<Protected><AdminSettings/></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter></QueryClientProvider>}

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
