import { useEffect,useState,type FormEvent } from 'react'
import { CalendarDays,Database,Palette,Save,ShieldCheck } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { Field,inputClass,textareaClass } from '@/components/admin/EntityDialog'
import { GlossaryText } from '@/components/glossary/GlossaryText'
import { supabaseConfigured } from '@/lib/supabase'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'

export default function AdminSettingsPage(){
 const {data}=useRoadmap();const {project}=useRoadmapMutations();const [draft,setDraft]=useState({name:'',description:'',start_date:'',target_weeks:10,max_weeks:12,total_amount:7800,currency:'SAR'})
 useEffect(()=>{if(data)setDraft({name:data.project.name,description:data.project.description,start_date:data.project.start_date??'',target_weeks:data.project.target_weeks,max_weeks:data.project.max_weeks,total_amount:Number(data.project.total_amount),currency:data.project.currency})},[data])
 if(!data)return null
 const save=(event:FormEvent)=>{event.preventDefault();project.mutate({id:data.project.id,patch:{...draft,start_date:draft.start_date||null,max_weeks:Math.max(draft.target_weeks,draft.max_weeks)}})}
 return <>
  <AdminPageHeader title="الإعدادات" description="تحكم في بيانات المشروع الرئيسية التي تظهر في الخطة والإحصائيات."/>
  <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><form onSubmit={save} className="surface rounded-2xl p-5"><div className="mb-5 flex items-start gap-3"><CalendarDays className="mt-1 h-5 w-5 text-primary"/><div><h2 className="font-black">بيانات المشروع والمدة</h2><p className="mt-1 text-sm leading-7 text-muted-foreground">اترك تاريخ البدء فارغًا حتى يبدأ التنفيذ فعليًا. عند تحديده يُحتسب الأسبوع الحالي تلقائيًا.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم المشروع"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className={inputClass}/></Field><Field label="تاريخ بدء المشروع"><input type="date" value={draft.start_date} onChange={e=>setDraft({...draft,start_date:e.target.value})} className={inputClass}/></Field><Field label="الأسابيع المستهدفة"><input type="number" min="1" max="12" value={draft.target_weeks} onChange={e=>setDraft({...draft,target_weeks:Number(e.target.value)})} className={inputClass}/></Field><Field label="الحد الأقصى للأسابيع"><input type="number" min={draft.target_weeks} max="12" value={draft.max_weeks} onChange={e=>setDraft({...draft,max_weeks:Number(e.target.value)})} className={inputClass}/></Field><Field label="قيمة العقد"><input type="number" min="0" step="0.01" value={draft.total_amount} onChange={e=>setDraft({...draft,total_amount:Number(e.target.value)})} className={inputClass}/></Field><Field label="العملة"><input value={draft.currency} maxLength={8} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})} className={inputClass}/></Field></div><div className="mt-4"><Field label="وصف المشروع"><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className={textareaClass}/></Field></div><button type="submit" disabled={project.isPending} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-primary-foreground disabled:opacity-60"><Save className="h-4 w-4"/>{project.isPending?'جارٍ الحفظ…':'حفظ إعدادات المشروع'}</button></form><div className="grid content-start gap-3"><Box icon={Database} title="Supabase" text={supabaseConfigured?'متصل؛ قاعدة البيانات هي مصدر الحقيقة المشترك بين الأجهزة.':'غير متصل؛ الواجهة في وضع المعاينة المحلي.'}/><Box icon={Palette} title="الهوية" text="Deep Amethyst #3E1848 + Whisper Lavender #E7E6F5 + خط ثمانية Serif Display."/><Box icon={ShieldCheck} title="الوصول والأمان" text="العرض العام للقراءة، بينما التعديل يتطلب Supabase Auth وتتحكم RLS في صلاحيات الوصول للسجلات."/></div></div>
 </>
}
function Box({icon:Icon,title,text}:any){return <article className="surface rounded-2xl p-4"><Icon className="h-5 w-5 text-primary"/><h2 className="mt-3 font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground"><GlossaryText text={text}/></p></article>}
