import { CheckCircle2,Circle,Flag } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'
import type { Milestone } from '@/features/roadmap/roadmap.types'

const groups={scope:'اعتماد النطاق',alpha:'بوابة Alpha',rc:'Release Candidate',final:'التسليم النهائي'} as const
const milestoneLabels:Record<Milestone['status'],string>={upcoming:'قادمة',ready:'جاهزة للمراجعة',approved:'معتمدة',delayed:'متأخرة'}

export default function AdminDeliverablesPage(){const {data}=useRoadmap();const {deliverable,milestone}=useRoadmapMutations();if(!data)return null;return <><AdminPageHeader title="التسليمات والمحطات" description="حدّث التسليمات وحالة بوابات الإنجاز؛ التغييرات تظهر مباشرة في عرض العميل."/><section className="mb-6"><h2 className="mb-4 text-xl font-black">بوابات الإنجاز</h2><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{data.milestones.map(item=><article key={item.id} className="surface rounded-2xl p-5"><div className="flex items-start gap-3"><Flag className="mt-1 h-5 w-5 shrink-0 text-primary"/><div className="min-w-0 flex-1"><span className="text-xs leading-6 text-muted-foreground">الأسبوع {item.week}</span><h3 className="mt-1 font-black leading-7">{item.title}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{item.acceptance_summary}</p><label className="mt-4 block text-sm font-bold">الحالة<select value={item.status} onChange={e=>milestone.mutate({id:item.id,patch:{status:e.target.value as Milestone['status']}})} className="mt-2 min-h-11 w-full rounded-xl border bg-background px-3">{Object.entries(milestoneLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div></div></article>)}</div></section><section><h2 className="mb-4 text-xl font-black">التسليمات</h2><div className="grid gap-4 xl:grid-cols-2">{Object.entries(groups).map(([key,label])=><article key={key} className="surface rounded-2xl p-5"><h3 className="font-black">{label}</h3><div className="mt-4 space-y-2">{data.deliverables.filter(item=>item.group_key===key).map(item=><button key={item.id} onClick={()=>deliverable.mutate({id:item.id,patch:{is_complete:!item.is_complete}})} className="flex min-h-12 w-full items-center gap-3 rounded-xl border bg-background px-4 text-right transition hover:bg-secondary"><span className="text-primary">{item.is_complete?<CheckCircle2 className="h-5 w-5"/>:<Circle className="h-5 w-5"/>}</span><span className="flex-1 font-medium leading-7">{item.title}</span><span className="text-xs text-muted-foreground">{item.is_complete?'مكتمل':'غير مكتمل'}</span></button>)}</div></article>)}</div></section></>}
