import { useState,type FormEvent } from 'react'
import { Eye,EyeOff,PenLine,Plus,Trash2 } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { ConfirmDialog } from '@/components/admin/ConfirmDialog'
import { EntityDialog,Field,inputClass,textareaClass } from '@/components/admin/EntityDialog'
import { GlossaryText } from '@/components/glossary/GlossaryText'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'
import type { ProjectUpdate } from '@/features/roadmap/roadmap.types'

type Draft=Pick<ProjectUpdate,'title'|'body'|'related_phase_id'|'published'>
const makeDraft=(item?:ProjectUpdate):Draft=>item?{title:item.title,body:item.body,related_phase_id:item.related_phase_id,published:item.published}:{title:'',body:'',related_phase_id:null,published:true}

export default function AdminUpdatesPage(){
 const {data}=useRoadmap();const mutations=useRoadmapMutations();const [dialogOpen,setDialogOpen]=useState(false);const [editing,setEditing]=useState<ProjectUpdate|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [deleteTarget,setDeleteTarget]=useState<ProjectUpdate|null>(null)
 if(!data)return null
 const openCreate=()=>{setEditing(null);setDraft(makeDraft());setDialogOpen(true)}
 const openEdit=(item:ProjectUpdate)=>{setEditing(item);setDraft(makeDraft(item));setDialogOpen(true)}
 const save=(event:FormEvent)=>{event.preventDefault();if(!draft?.title.trim()||!draft.body.trim())return;if(editing)mutations.updateEdit.mutate({id:editing.id,patch:draft});else mutations.update.mutate(draft);setDialogOpen(false)}
 const remove=()=>{if(!deleteTarget)return;mutations.updateDelete.mutate(deleteTarget.id,{onSettled:()=>setDeleteTarget(null)})}
 return <>
  <AdminPageHeader title="التحديثات" description="أضف تحديثات العميل وعدّلها أو أخفها أو احذفها. التحديث غير المنشور يبقى ظاهرًا لك فقط داخل الإدارة." action={<button type="button" onClick={openCreate} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground"><Plus className="h-4 w-4"/>إضافة تحديث</button>}/>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.updates.map(item=><article key={item.id} className="surface rounded-2xl p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString('ar-SA')}</span><h2 className="mt-1 font-black leading-7"><GlossaryText text={item.title}/></h2></div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${item.published?'bg-success/10 text-success':'bg-secondary text-muted-foreground'}`}>{item.published?<Eye className="h-3.5 w-3.5"/>:<EyeOff className="h-3.5 w-3.5"/>}{item.published?'منشور':'مخفي'}</span></div><p className="mt-3 text-sm leading-7 text-muted-foreground"><GlossaryText text={item.body}/></p>{item.related_phase_id&&<div className="mt-3 rounded-xl bg-secondary/45 p-2 text-xs text-muted-foreground">مرتبط بـ {data.phases.find(phase=>phase.id===item.related_phase_id)?.name??'مرحلة محذوفة'}</div>}<div className="mt-4 flex items-center justify-between gap-2 border-t pt-3"><button type="button" onClick={()=>mutations.updateEdit.mutate({id:item.id,patch:{published:!item.published}})} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm font-bold hover:bg-secondary">{item.published?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}{item.published?'إخفاء':'نشر'}</button><div className="flex gap-1"><button type="button" onClick={()=>openEdit(item)} aria-label="تعديل التحديث" className="grid h-11 w-11 place-items-center rounded-xl border hover:bg-secondary"><PenLine className="h-4 w-4"/></button><button type="button" onClick={()=>setDeleteTarget(item)} aria-label="حذف التحديث" className="grid h-11 w-11 place-items-center rounded-xl border text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div>
  {!data.updates.length&&<div className="surface rounded-2xl p-8 text-center text-muted-foreground">لا توجد تحديثات بعد. استخدم «إضافة تحديث» لنشر أول تحديث للعميل.</div>}
  <EntityDialog open={dialogOpen&&!!draft} title={editing?'تعديل التحديث':'إضافة تحديث'} description="اجعل النص مختصرًا وواضحًا للعميل. يمكنك حفظه مخفيًا ثم نشره لاحقًا." onClose={()=>setDialogOpen(false)}>{draft&&<form onSubmit={save} className="space-y-4"><Field label="العنوان"><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className={inputClass} placeholder="مثال: اكتمال أساس تطبيق React Native"/></Field><Field label="التفاصيل"><textarea required value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} className={textareaClass} placeholder="ماذا تم؟ وما الخطوة التالية؟"/></Field><Field label="المرحلة المرتبطة"><select value={draft.related_phase_id??''} onChange={e=>setDraft({...draft,related_phase_id:e.target.value||null})} className={inputClass}><option value="">بدون ارتباط بمرحلة</option>{data.phases.map(phase=><option key={phase.id} value={phase.id}>{phase.name}</option>)}</select></Field><label className="flex min-h-11 items-center gap-3 rounded-xl border px-3"><input type="checkbox" checked={draft.published} onChange={e=>setDraft({...draft,published:e.target.checked})}/>{draft.published?<Eye className="h-4 w-4"/>:<EyeOff className="h-4 w-4"/>}<span className="font-bold">منشور للعميل</span></label><div className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={()=>setDialogOpen(false)} className="min-h-11 rounded-xl border px-5 font-bold">إلغاء</button><button type="submit" disabled={mutations.update.isPending||mutations.updateEdit.isPending} className="min-h-11 rounded-xl bg-primary px-5 font-bold text-primary-foreground disabled:opacity-50">{editing?'حفظ التعديل':'إضافة التحديث'}</button></div></form>}</EntityDialog>
  <ConfirmDialog open={!!deleteTarget} title="حذف التحديث؟" description={deleteTarget?`سيتم حذف «${deleteTarget.title}» نهائيًا.`:''} busy={mutations.updateDelete.isPending} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/>
 </>
}
