import { useEffect,useState } from 'react'
import { Database,Palette,ShieldCheck,CalendarDays,Save } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { supabaseConfigured } from '@/lib/supabase'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'

export default function AdminSettingsPage(){const {data}=useRoadmap();const {project}=useRoadmapMutations();const [startDate,setStartDate]=useState('');const [description,setDescription]=useState('');useEffect(()=>{if(data){setStartDate(data.project.start_date??'');setDescription(data.project.description)}},[data]);if(!data)return null;const save=()=>project.mutate({id:data.project.id,patch:{start_date:startDate||null,description}});return <><AdminPageHeader title="الإعدادات" description="إعدادات المشروع والاتصال. تاريخ البدء هو المرجع الذي يُحتسب منه الأسبوع الحالي تلقائيًا."/><div className="mb-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="surface rounded-2xl p-5"><div className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-primary"/><div><h2 className="font-black">بداية المشروع</h2><p className="mt-1 text-sm leading-7 text-muted-foreground">اترك التاريخ فارغًا ما دام التنفيذ لم يبدأ. عند تحديده سيظهر الأسبوع الحالي تلقائيًا في لوحة العميل.</p></div></div><label className="mt-5 block text-sm font-bold">تاريخ بدء المشروع<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border bg-background px-4"/></label><label className="mt-5 block text-sm font-bold">وصف المشروع<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="mt-2 w-full rounded-xl border bg-background p-4 leading-7"/></label><button onClick={save} disabled={project.isPending} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-primary-foreground disabled:opacity-60"><Save className="h-4 w-4"/>{project.isPending?'جارٍ الحفظ…':'حفظ إعدادات المشروع'}</button></section><div className="grid gap-4"><Box icon={Database} title="Supabase" text={supabaseConfigured?'متصل عبر متغيرات البيئة؛ البيانات مشتركة بين الأجهزة.':'غير متصل حاليًا؛ ستعمل الواجهة بمعاينة محلية حتى إضافة بيانات Supabase.'}/><Box icon={Palette} title="الهوية" text="Deep Amethyst #3E1848 + Whisper Lavender #E7E6F5 + خط ثمانية Serif Display."/><Box icon={ShieldCheck} title="الوصول" text="العرض العام للقراءة؛ الإدارة تتطلب Supabase Auth وسياسات RLS."/></div></div></>}
function Box({icon:Icon,title,text}:any){return <article className="surface rounded-2xl p-5"><Icon className="h-5 w-5 text-primary"/><h2 className="mt-4 font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></article>}
