import { useState,type FormEvent } from 'react'
import { CalendarDays,CreditCard,PenLine,Plus,Trash2,WalletCards } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { ConfirmDialog } from '@/components/admin/ConfirmDialog'
import { EntityDialog,Field,inputClass,textareaClass } from '@/components/admin/EntityDialog'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'
import { formatSar } from '@/lib/format'
import type { Payment } from '@/features/roadmap/roadmap.types'

const statusLabel:Record<Payment['status'],string>={pending:'قادمة',due:'مستحقة',paid:'مدفوعة'}
type Draft=Omit<Payment,'id'|'project_id'>
const makeDraft=(payment?:Payment,sequence=1):Draft=>payment?{sequence:payment.sequence,percentage:Number(payment.percentage),amount:Number(payment.amount),trigger_title:payment.trigger_title,trigger_week:payment.trigger_week,status:payment.status,due_date:payment.due_date,paid_at:payment.paid_at,notes:payment.notes}:{sequence,percentage:0,amount:0,trigger_title:'',trigger_week:null,status:'pending',due_date:null,paid_at:null,notes:''}

export default function AdminPaymentsPage(){
 const {data}=useRoadmap();const mutations=useRoadmapMutations();const [dialogOpen,setDialogOpen]=useState(false);const [editing,setEditing]=useState<Payment|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [deleteTarget,setDeleteTarget]=useState<Payment|null>(null)
 if(!data)return null
 const paid=data.payments.filter(item=>item.status==='paid').reduce((sum,item)=>sum+Number(item.amount),0)
 const due=data.payments.filter(item=>item.status==='due').reduce((sum,item)=>sum+Number(item.amount),0)
 const remaining=Math.max(0,Number(data.project.total_amount)-paid)
 const percentTotal=Math.round(data.payments.reduce((sum,item)=>sum+Number(item.percentage),0)*100)/100
 const openCreate=()=>{setEditing(null);setDraft(makeDraft(undefined,data.payments.length+1));setDialogOpen(true)}
 const openEdit=(payment:Payment)=>{setEditing(payment);setDraft(makeDraft(payment));setDialogOpen(true)}
 const save=(event:FormEvent)=>{event.preventDefault();if(!draft||draft.amount<=0||draft.percentage<0)return;const row={...draft,paid_at:draft.status==='paid'?(draft.paid_at??new Date().toISOString()):null};if(editing)mutations.payment.mutate({id:editing.id,patch:row});else mutations.paymentCreate.mutate({id:crypto.randomUUID(),project_id:data.project.id,...row});setDialogOpen(false)}
 const remove=()=>{if(!deleteTarget)return;mutations.paymentDelete.mutate(deleteTarget.id,{onSettled:()=>setDeleteTarget(null)})}
 return <>
  <AdminPageHeader title="إدارة الدفعات" description="تحكم في المبلغ والنسبة ونقطة الاستحقاق والتواريخ والحالة. هذه الصفحة للتتبع ولا تنفذ عملية دفع مالي." action={<button type="button" onClick={openCreate} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground"><Plus className="h-4 w-4"/>إضافة دفعة</button>}/>
  <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="قيمة العقد" value={formatSar(data.project.total_amount)} icon={CreditCard}/><Metric label="المدفوع" value={formatSar(paid)} icon={WalletCards}/><Metric label="المتبقي" value={formatSar(remaining)} icon={CreditCard}/><Metric label="المستحق الآن" value={formatSar(due)} icon={CalendarDays}/></div>
  {percentTotal!==100&&<div className="mb-4 rounded-2xl border border-warning/20 bg-warning/10 p-3 text-sm leading-7 text-warning">مجموع نسب الدفعات حاليًا {percentTotal}%. يمكنك متابعة التحرير، لكن يفضل أن يكون المجموع 100% عند اعتماد الخطة.</div>}
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.payments.map(payment=><article key={payment.id} className="surface rounded-2xl p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-primary">الدفعة {payment.sequence}</span><h2 className="mt-1 font-black leading-7">{payment.trigger_title}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${payment.status==='paid'?'bg-success/10 text-success':payment.status==='due'?'bg-warning/10 text-warning':'bg-secondary text-muted-foreground'}`}>{statusLabel[payment.status]}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Info label="المبلغ" value={formatSar(payment.amount)}/><Info label="النسبة" value={`${payment.percentage}%`}/><Info label="الأسبوع" value={payment.trigger_week?String(payment.trigger_week):'—'}/><Info label="تاريخ الاستحقاق" value={payment.due_date??'غير محدد'}/></div>{payment.notes&&<p className="mt-3 rounded-xl bg-secondary/45 p-3 text-sm leading-7 text-muted-foreground">{payment.notes}</p>}<select value={payment.status} onChange={e=>mutations.payment.mutate({id:payment.id,patch:{status:e.target.value as Payment['status'],paid_at:e.target.value==='paid'?(payment.paid_at??new Date().toISOString()):null}})} className={`${inputClass} mt-3`}>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><div className="mt-3 flex justify-end gap-1 border-t pt-3"><button type="button" onClick={()=>openEdit(payment)} aria-label="تعديل الدفعة" className="grid h-11 w-11 place-items-center rounded-xl border hover:bg-secondary"><PenLine className="h-4 w-4"/></button><button type="button" onClick={()=>setDeleteTarget(payment)} aria-label="حذف الدفعة" className="grid h-11 w-11 place-items-center rounded-xl border text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>
  <EntityDialog open={dialogOpen&&!!draft} title={editing?'تعديل الدفعة':'إضافة دفعة'} description="يمكن تعديل المبلغ والنسبة ونقطة الاستحقاق دون تغيير بقية الدفعات." onClose={()=>setDialogOpen(false)}>{draft&&<form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="رقم الدفعة"><input type="number" min="1" value={draft.sequence} onChange={e=>setDraft({...draft,sequence:Number(e.target.value)})} className={inputClass}/></Field><Field label="الحالة"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Payment['status']})} className={inputClass}>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="المبلغ"><input type="number" min="0.01" step="0.01" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})} className={inputClass}/></Field><Field label="النسبة %"><input type="number" min="0" max="100" step="0.01" value={draft.percentage} onChange={e=>setDraft({...draft,percentage:Number(e.target.value)})} className={inputClass}/></Field><Field label="نقطة الاستحقاق"><input required value={draft.trigger_title} onChange={e=>setDraft({...draft,trigger_title:e.target.value})} className={inputClass}/></Field><Field label="أسبوع الاستحقاق"><input type="number" min="1" max="12" value={draft.trigger_week??''} onChange={e=>setDraft({...draft,trigger_week:e.target.value?Number(e.target.value):null})} className={inputClass}/></Field><Field label="تاريخ الاستحقاق"><input type="date" value={draft.due_date??''} onChange={e=>setDraft({...draft,due_date:e.target.value||null})} className={inputClass}/></Field><Field label="تاريخ الدفع"><input type="datetime-local" value={draft.paid_at?draft.paid_at.slice(0,16):''} onChange={e=>setDraft({...draft,paid_at:e.target.value?new Date(e.target.value).toISOString():null})} className={inputClass}/></Field></div><Field label="ملاحظات"><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} className={textareaClass}/></Field><div className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={()=>setDialogOpen(false)} className="min-h-11 rounded-xl border px-5 font-bold">إلغاء</button><button type="submit" disabled={mutations.payment.isPending||mutations.paymentCreate.isPending} className="min-h-11 rounded-xl bg-primary px-5 font-bold text-primary-foreground disabled:opacity-50">{editing?'حفظ التعديل':'إضافة الدفعة'}</button></div></form>}</EntityDialog>
  <ConfirmDialog open={!!deleteTarget} title="حذف الدفعة؟" description={deleteTarget?`سيتم حذف الدفعة رقم ${deleteTarget.sequence} (${formatSar(deleteTarget.amount)}) من جدول المشروع.`:''} busy={mutations.paymentDelete.isPending} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/>
 </>
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <article className="surface rounded-2xl p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold text-muted-foreground">{label}</span><Icon className="h-5 w-5 text-primary"/></div><b className="mt-3 block text-xl font-black">{value}</b></article>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-secondary/45 p-3"><span className="block text-xs text-muted-foreground">{label}</span><b className="mt-1 block text-sm">{value}</b></div>}
