import { Activity,ListChecks,CreditCard,Eye,Wifi } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { deriveRoadmapMetrics } from '@/features/roadmap/roadmap.metrics'
import { KpiCard } from '@/components/dashboard/KpiCard'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { formatSar,pct } from '@/lib/format'
import { supabaseConfigured } from '@/lib/supabase'
export default function AdminDashboardPage(){const {data}=useRoadmap();if(!data)return null;const metrics=deriveRoadmapMetrics(data);return <><AdminPageHeader title="لوحة الإدارة" description="ملخص مباشر لما سيراه العميل وما يحتاج تدخلًا منك." action={<Link to="/" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-card px-4 text-sm font-bold"><Eye className="h-4 w-4"/>معاينة العميل</Link>}/><div className={`mb-5 flex items-center gap-3 rounded-2xl border p-4 text-sm ${supabaseConfigured?'border-success/20 bg-success/10':'border-warning/20 bg-warning/10'}`}><Wifi className="h-5 w-5"/><span>{supabaseConfigured?'Supabase متصل — التعديلات تظهر للعميل مباشرة.':'وضع المعاينة المحلي — سيصبح التحديث مشتركًا بين الأجهزة بعد ربط Supabase.'}</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="التقدم" value={pct(metrics.overallProgress)} detail={metrics.currentWeek?`الأسبوع ${metrics.currentWeek}`:'لم يبدأ بعد'} icon={Activity}/><KpiCard label="نشطة/مراجعة" value={`${metrics.activeTasks}`} detail={`من ${metrics.totalTasks} مهمة`} icon={ListChecks}/><KpiCard label="قيمة العقد" value={formatSar(data.project.total_amount)} detail="3 دفعات" icon={CreditCard}/><KpiCard label="المعاينة" value="Public" detail="قراءة فقط" icon={Eye}/></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Quick to="/admin/tasks" title="تحديث المهام" text="غيّر الحالة ونسبة الإنجاز؛ بقية الإحصائيات تتحدث تلقائيًا."/><Quick to="/admin/payments" title="تحديث الدفعات" text="سجّل الدفعة كقادمة أو مستحقة أو مدفوعة."/><Quick to="/admin/deliverables" title="التسليمات والمحطات" text="حدّث بوابات الإنجاز والتسليمات من مكان واحد."/><Quick to="/admin/settings" title="إعداد بدء المشروع" text="حدد تاريخ البدء ليتم احتساب الأسبوع الحالي تلقائيًا."/></div></>}
function Quick({to,title,text}:{to:string;title:string;text:string}){return <Link to={to} className="surface rounded-2xl p-5 transition hover:-translate-y-0.5 hover:shadow-md"><h2 className="text-lg font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></Link>}
