import { useState,type FormEvent } from 'react'
import { CalendarRange,LayoutGrid,PenLine,Plus,Trash2 } from 'lucide-react'
import { AdminPageHeader } from '@/components/admin/AdminPageHeader'
import { ConfirmDialog } from '@/components/admin/ConfirmDialog'
import { EntityDialog,Field,inputClass,textareaClass } from '@/components/admin/EntityDialog'
import { GlossaryPanel } from '@/components/glossary/GlossaryPanel'
import { GlossaryText } from '@/components/glossary/GlossaryText'
import { GanttGrid } from '@/components/timeline/GanttGrid'
import { useRoadmap } from '@/features/roadmap/roadmap.queries'
import { useRoadmapMutations } from '@/features/roadmap/roadmap.mutations'
import { pct } from '@/lib/format'
import type { Phase } from '@/features/roadmap/roadmap.types'

const statusLabel={planned:'مخطط',active:'قيد التنفيذ',done:'مكتمل',blocked:'متوقف / مؤجل'} as const
type Draft=Pick<Phase,'name'|'description'|'start_week'|'end_week'|'sort_order'|'is_public'>
const makeDraft=(phase?:Phase):Draft=>phase?{name:phase.name,description:phase.description,start_week:phase.start_week,end_week:phase.end_week,sort_order:phase.sort_order,is_public:phase.is_public}:{name:'',description:'',start_week:1,end_week:1,sort_order:1,is_public:true}

export default function AdminTimelinePage(){
 const {data}=useRoadmap();const mutations=useRoadmapMutations();const [view,setView]=useState<'cards'|'gantt'>('cards');const [dialogOpen,setDialogOpen]=useState(false);const [editing,setEditing]=useState<Phase|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [deleteTarget,setDeleteTarget]=useState<Phase|null>(null)
 if(!data)return null
 const openCreate=()=>{setEditing(null);setDraft({...makeDraft(),sort_order:data.phases.length+1});setDialogOpen(true)}
 const openEdit=(phase:Phase)=>{setEditing(phase);setDraft(makeDraft(phase));setDialogOpen(true)}
 const save=(event:FormEvent)=>{event.preventDefault();if(!draft||!draft.name.trim())return;const clean={...draft,start_week:Math.max(1,Math.min(12,draft.start_week)),end_week:Math.max(draft.start_week,Math.min(12,draft.end_week))};if(editing)mutations.phase.mutate({id:editing.id,patch:clean});else mutations.phaseCreate.mutate({id:crypto.randomUUID(),project_id:data.project.id,progress:0,status:'planned',...clean});setDialogOpen(false)}
 const remove=()=>{if(!deleteTarget)return;mutations.phaseDelete.mutate(deleteTarget.id,{onSettled:()=>setDeleteTarget(null)})}
 return <>
  <AdminPageHeader title="إدارة الخطة الزمنية" description="عدّل بنية المراحل والأسابيع والترتيب. حالة كل مرحلة وتقدمها محسوبان تلقائيًا من مهامها." action={<div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setView(view==='cards'?'gantt':'cards')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-card px-4 font-bold">{view==='cards'?<CalendarRange className="h-4 w-4"/>:<LayoutGrid className="h-4 w-4"/>}{view==='cards'?'عرض المخطط':'عرض البطاقات'}</button><button type="button" onClick={openCreate} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground"><Plus className="h-4 w-4"/>إضافة مرحلة</button></div>}/>
  {view==='cards'?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{data.phases.map(phase=><article key={phase.id} className="surface rounded-2xl p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs leading-6 text-muted-foreground">الأسبوع {phase.start_week}–{phase.end_week}</span><h2 className="mt-1 font-black leading-7"><GlossaryText text={phase.name}/></h2></div><span className="rounded-lg bg-secondary px-2 py-1 text-xs font-black">{pct(phase.progress)}</span></div><p className="mt-2 text-sm leading-7 text-muted-foreground"><GlossaryText text={phase.description}/></p><div className="mt-4 h-2 rounded-full bg-secondary"><div className="h-2 rounded-full bg-primary transition-[width] duration-200" style={{width:`${phase.progress}%`}}/></div><div className="mt-3 flex items-center justify-between gap-2"><div><span className="text-xs font-bold">{statusLabel[phase.status]}</span><span className="mr-2 text-xs text-muted-foreground">ترتيب {phase.sort_order}</span></div><div className="flex gap-1"><button type="button" onClick={()=>openEdit(phase)} aria-label="تعديل المرحلة" className="grid h-11 w-11 place-items-center rounded-xl border hover:bg-secondary"><PenLine className="h-4 w-4"/></button><button type="button" onClick={()=>setDeleteTarget(phase)} aria-label="حذف المرحلة" className="grid h-11 w-11 place-items-center rounded-xl border text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div>:<GanttGrid phases={data.phases} milestones={data.milestones}/>} 
  <GlossaryPanel/>
  <EntityDialog open={dialogOpen&&!!draft} title={editing?'تعديل المرحلة':'إضافة مرحلة'} description="التقدم والحالة غير قابلين للتحرير هنا لأنهما يُحسبان من المهام التابعة للمرحلة." onClose={()=>setDialogOpen(false)}>{draft&&<form onSubmit={save} className="space-y-4"><Field label="اسم المرحلة"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className={inputClass}/></Field><Field label="الوصف"><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className={textareaClass}/></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="أسبوع البداية"><input type="number" min="1" max="12" value={draft.start_week} onChange={e=>setDraft({...draft,start_week:Number(e.target.value)})} className={inputClass}/></Field><Field label="أسبوع النهاية"><input type="number" min={draft.start_week} max="12" value={draft.end_week} onChange={e=>setDraft({...draft,end_week:Number(e.target.value)})} className={inputClass}/></Field><Field label="ترتيب العرض"><input type="number" min="1" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})} className={inputClass}/></Field></div><label className="flex min-h-11 items-center gap-3 rounded-xl border px-3"><input type="checkbox" checked={draft.is_public} onChange={e=>setDraft({...draft,is_public:e.target.checked})}/><span className="font-bold">تظهر المرحلة للعميل</span></label><div className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={()=>setDialogOpen(false)} className="min-h-11 rounded-xl border px-5 font-bold">إلغاء</button><button type="submit" disabled={mutations.phase.isPending||mutations.phaseCreate.isPending} className="min-h-11 rounded-xl bg-primary px-5 font-bold text-primary-foreground disabled:opacity-50">{editing?'حفظ التعديل':'إضافة المرحلة'}</button></div></form>}</EntityDialog>
  <ConfirmDialog open={!!deleteTarget} title="حذف المرحلة؟" description={deleteTarget?`حذف «${deleteTarget.name}» سيحذف أيضًا المهام التابعة لها من قاعدة البيانات. استخدم هذا الإجراء فقط إذا كان الحذف مقصودًا.`:''} busy={mutations.phaseDelete.isPending} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/>
 </>
}
